### ISSUE TITLE
Getting an artifact version from a semver file

### ISSUE THREAD

**Issue by aegershman** [nulldriver/maven-resource#24]
I'd like to dynamically specify the artifact `version` which is pulled from a maven repository. Specifically, I'd like it to be from the [`semver` resource](https://github.com/concourse/semver-resource):

```yml
- name: deploy
  plan:
  - get: version
  - get: artifact
    version:
      path: version/version # pulls 'version' from the contents of the semver version file
```

Is this possible / a use case you would consider supporting?
