### ISSUE TITLE
"The goal you specified requires a project to execute but there is no POM in this directory"

### ISSUE THREAD

**Issue by KPull** [nulldriver/maven-resource#43]
I've having trouble executing this resource with the following pipeline:

```yaml
jobs:
  - name: build
    plan:
      - get: source-code
        trigger: true

      - task: maven-package
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.6.3-openjdk-11
          inputs:
            - name: source-code
              path: source-code
          outputs:
            - name: binaries
              path: source-code/target
          run:
            dir: source-code
            path: mvn
            args:
              - package

      - put: package
        params:
          file: binaries/application-*.jar
          pom_file: source-code/pom.xml

    on_failure:
      put: notification
      params:
        message: ":warning: `application` has failed tests"
```

However, when running the Pipeline in Concourse, I get the following error:

```
The goal you specified requires a project to execute but there is no POM in this directory (/tmp/build/put). Please verify you invoked Maven from the correct directory. -> [Help 1]`
```

I've tried version 1.3.6 and the latest versions of this resource however both are giving us the same error. Can you please point out what I'm doing wrong, please?
